node {
    stage('Release scan orchestrator') {
        def projects = [:]
        def snyk_org = "ed4a4d1b-cc26-46ba-9142-07f88b6a50f4"
        def snyk_scan = "monitor"

        projects['SFE-Client-App'] = {
            build job: 'executor', parameters: [
                string(name: 'snyk_org', value: snyk_org),
                string(name: 'git_repo', value: "github.com/SymphonyOSF/SFE-Client-App.git"),
                string(name: 'git_hash', value: "master"),
                string(name: 'prj_type', value: 'nodejs'),
                string(name: 'snyk_scan', value: snyk_scan)
            ],
            wait: true
        }

        projects['SFE-Admin-Compliance'] = {
            build job: 'executor', parameters: [
                string(name: 'snyk_org', value: snyk_org),
                string(name: 'git_repo', value: "github.com/SymphonyOSF/SFE-Admin-Compliance.git"),
                string(name: 'git_hash', value: "dev"),
                string(name: 'prj_type', value: 'nodejs'),
                string(name: 'snyk_scan', value: snyk_scan)
            ],
            wait: true
        }

        projects['SFE-Login'] = {
            build job: 'executor', parameters: [
                string(name: 'snyk_org', value: snyk_org),
                string(name: 'git_repo', value: "github.com/SymphonyOSF/SFE-Login.git"),
                string(name: 'git_hash', value: "master),
                string(name: 'prj_type', value: 'nodejs'),
                string(name: 'snyk_scan', value: snyk_scan)
            ],
            wait: true
        }

        projects['Embedded-Chat'] = {
            build job: 'executor', parameters: [
                string(name: 'snyk_org', value: snyk_org),
                string(name: 'git_repo', value: "github.com/SymphonyOSF/Embedded-Chat.git"),
                string(name: 'git_hash', value: "dev"),
                string(name: 'prj_type', value: 'nodejs'),
                string(name: 'snyk_scan', value: snyk_scan)
            ],
            wait: true
        }


        parallel projects
    }
}
