node {
    stage('Release scan orchestrator') {
        def projects = [:]
        def snyk_org = "1533ded9-dcfa-4e40-ba01-3e05f03b60e0"
        def snyk_scan = "monitor"

        projects['client'] = {
            build job: 'executor', parameters: [
                string(name: 'snyk_org', value: snyk_org),
                string(name: 'git_repo', value: "github.com/SymphonyOSF/SFE-Client-App.git"),
                string(name: 'git_hash', value: "20.12"),
                string(name: 'prj_type', value: 'nodejs'),
                string(name: 'snyk_scan', value: snyk_scan)
            ],
            wait: true
        }

        projects['admin'] = {
            build job: 'executor', parameters: [
                string(name: 'snyk_org', value: snyk_org),
                string(name: 'git_repo', value: "github.com/SymphonyOSF/SFE-Admin-Compliance.git"),
                string(name: 'git_hash', value: "20.12"),
                string(name: 'prj_type', value: 'nodejs'),
                string(name: 'snyk_scan', value: snyk_scan)
            ],
            wait: true
        }

        projects['login'] = {
            build job: 'executor', parameters: [
                string(name: 'snyk_org', value: snyk_org),
                string(name: 'git_repo', value: "github.com/SymphonyOSF/SFE-Login.git"),
                string(name: 'git_hash', value: "20.12"),
                string(name: 'prj_type', value: 'nodejs'),
                string(name: 'snyk_scan', value: snyk_scan)
            ],
            wait: true
        }

        projects['sbe'] = {
            build job: 'executor', parameters: [
                string(name: 'snyk_org', value: snyk_org),
                string(name: 'git_repo', value: "github.com/SymphonyOSF/SBE.git"),
                string(name: 'git_hash', value: "20.12"),
                string(name: 'prj_type', value: "java"),
                string(name: 'java_version', value: '8'),
                string(name: 'java_params', value: "-DsymphonySkipUnitTests=true -DsymphonySkipIntegrationTests=true -PSymphony,SharedResources"),
                string(name: 'snyk_scan', value: snyk_scan)
            ],
            wait: true
        }

        projects['agent'] = {
            build job: 'executor', parameters: [
                string(name: 'snyk_org', value: snyk_org),
                string(name: 'git_repo', value: "github.com/SymphonyOSF/symphony-agent.git"),
                string(name: 'git_hash', value: "20.12"),
                string(name: 'prj_type', value: "java"),
                string(name: 'java_version', value: '8'),
                string(name: 'snyk_scan', value: snyk_scan)
            ],
            wait: true
        }

        parallel projects
    }
}