node {
    stage('Release scan orchestrator') {
        def projects = [:]
        def snyk_org = "711c53b6-a85d-4a51-a34f-42552cc8572e"
        def snyk_scan = "monitor"

        projects['BFF'] = {
            build job: 'executor', parameters: [
                string(name: 'snyk_org', value: snyk_org),
                string(name: 'git_repo', value: "github.com/SymphonyOSF/BFF.git"),
                string(name: 'git_hash', value: "master"),
                string(name: 'prj_type', value: 'java'),
                string(name: 'java_version', value: '11'),
                string(name: 'java_params', value: "-DsymphonySkipUnitTests=true -DsymphonySkipIntegrationTests=true"),
                string(name: 'snyk_scan', value: snyk_scan)
            ],
            wait: true
        }

        parallel projects
    }
}
